return {
  default_mappings = true,
  builtin_marks = { ".", "<", ">", "^" },
  cyclic = false,
  force_write_shada = false,
  refresh_interval = 250,
  sign_priority = { lower=10, upper=15, builtin=8, bookmark=20 },
  excluded_filetypes = {
    '',
    'notify',
    'NvimTree',
    'saga_codeaction',
    'sagarename',
    'sagacallhierarchy',
    'dap-float',
    'dap-repl',
    'dapui_hover',
    'dapui_console',
    'dapui_repl',
    'dapui_watches',
    'dapui_stacks',
    'dapui_scopes',
    'dapui_breakpoints',
    'harpoon',
    'btags',
    'bookmarks',
  },
  bookmark_1 = { sign = "1", virt_text = "🐮 1", annotate = false },
  bookmark_2 = { sign = "2", virt_text = "🐮 2", annotate = false },
  bookmark_3 = { sign = "3", virt_text = "🐮 3", annotate = false },
  bookmark_4 = { sign = "4", virt_text = "🐮 4", annotate = false },
  bookmark_5 = { sign = "5", virt_text = "🐮 5", annotate = false },
  bookmark_6 = { sign = "6", virt_text = "🐮 6", annotate = false },
  bookmark_7 = { sign = "7", virt_text = "🐮 7", annotate = false },
  bookmark_8 = { sign = "8", virt_text = "🐮 8", annotate = false },
  bookmark_9 = { sign = "9", virt_text = "🐮 9", annotate = false },
  bookmark_0 = { sign = "🐮", virt_text = "🐮 @", annotate = false },
  mappings = {
    next_bookmark1 = "]1",
    prev_bookmark1 = "[1",
    next_bookmark2 = "]2",
    prev_bookmark2 = "[2",
    next_bookmark3 = "]3",
    prev_bookmark3 = "[3",
    next_bookmark4 = "]4",
    prev_bookmark4 = "[4",
    next_bookmark5 = "]5",
    prev_bookmark5 = "[5",
    next_bookmark6 = "]6",
    prev_bookmark6 = "[6",
    next_bookmark7 = "]7",
    prev_bookmark7 = "[7",
    next_bookmark8 = "]8",
    prev_bookmark8 = "[8",
    next_bookmark9 = "]9",
    prev_bookmark9 = "[9",
    next_bookmark0 = "]0",
    prev_bookmark0 = "[0",
    next_bookmark = "]`",
    prev_bookmark = "[`",
    annotate = "mm",
  }
}
